set linesize 32000
set pagesize 1000
set long 2000000000
set longchunksize 1000
set head off;
set verify off;
set termout off;
 
column u new_value us noprint;
column n new_value ns noprint;
 
select name n from v$database;
select user u from dual;
set sqlprompt &ns:&us>

set head on
set echo on
set termout on
set trimspool on

spool &ns.checksuppl.log


select * from dba_users where username='AWSDMS';
select * from dba_role_privs where grantee='AWSDMS';
select * from dba_sys_privs where grantee='AWSDMS';
select * from dba_tab_privs where grantee='AWSDMS';

SELECT SUPPLEMENTAL_LOG_DATA_MIN,LOG_MODE FROM V$DATABASE;

SELECT *
FROM dba_log_groups
WHERE owner = 'TKCSOWNER'
AND table_name in
(
'ACCESSPROFILE',
'ACCRUALPROFILE',
'ASSIGNPAYRULE',
'AVLBLTYPTRNDAP',
'BADGEASSIGN',
'BASEWAGERTHIST',
'COMBHOMEACCT',
'CONTACTTYPE',
'EFFPRSNACSASGN',
'EMAILADDRESS',
'EMPGRPSCHEDMM',
'EMPLOYMENTSTAT',
'GROUPSCHEDULE',
'HOLIDAY',
'JAIDS',
'LABORACCT',
'LABORACCTSET',
'LOGONPROFILE',
'ORGSET',
'OVERRIDETYPE',
'PAYCODE',
'PAYCODEDAP',
'PAYRULE',
'PAYRULEIDS',
'PERSON',
'PERSONEXPHRSMM',
'PERSONSTATUSMM',
'PHONENUMBER',
'POSTALADDRESS',
'PREFERENCEPROF',
'PRSNACCSASSIGN',
'PRSNLICTYPEMM',
'PUNCHEVENT',
'REPORTDAP',
'TERMINALRULE',
'TIMEENTRYTYPE',
'TIMESHEETITEM',
'TIMEZONE',
'TMSHTITEMTYPE',
'TOTALEVENTTS',
'USERACCOUNT',
'WAGEPROFILE',
'WDMDEVICEGROUP',
'WFCJOBORG',
'WORKERTYPE',
'WORKRULEDAP',
'WORKRULEIDS',
'WTKEMPLOYEE'
)
order by table_name;

select * from
dba_tab_privs
where
OWNER = 'TKCSOWNER'
AND table_name in
(
'ACCESSPROFILE',
'ACCRUALPROFILE',
'ASSIGNPAYRULE',
'AVLBLTYPTRNDAP',
'BADGEASSIGN',
'BASEWAGERTHIST',
'COMBHOMEACCT',
'CONTACTTYPE',
'EFFPRSNACSASGN',
'EMAILADDRESS',
'EMPGRPSCHEDMM',
'EMPLOYMENTSTAT',
'GROUPSCHEDULE',
'HOLIDAY',
'JAIDS',
'LABORACCT',
'LABORACCTSET',
'LOGONPROFILE',
'ORGSET',
'OVERRIDETYPE',
'PAYCODE',
'PAYCODEDAP',
'PAYRULE',
'PAYRULEIDS',
'PERSON',
'PERSONEXPHRSMM',
'PERSONSTATUSMM',
'PHONENUMBER',
'POSTALADDRESS',
'PREFERENCEPROF',
'PRSNACCSASSIGN',
'PRSNLICTYPEMM',
'PUNCHEVENT',
'REPORTDAP',
'TERMINALRULE',
'TIMEENTRYTYPE',
'TIMESHEETITEM',
'TIMEZONE',
'TMSHTITEMTYPE',
'TOTALEVENTTS',
'USERACCOUNT',
'WAGEPROFILE',
'WDMDEVICEGROUP',
'WFCJOBORG',
'WORKERTYPE',
'WORKRULEDAP',
'WORKRULEIDS',
'WTKEMPLOYEE') and
GRANTEE = 'AWSDMS'
and
PRIVILEGE = 'SELECT'
order by table_name;

SELECT *
FROM ALL_CONSTRAINTS
WHERE owner = 'TKCSOWNER'
AND table_name in
(
'ACCESSPROFILE',
'ACCRUALPROFILE',
'ASSIGNPAYRULE',
'AVLBLTYPTRNDAP',
'BADGEASSIGN',
'BASEWAGERTHIST',
'COMBHOMEACCT',
'CONTACTTYPE',
'EFFPRSNACSASGN',
'EMAILADDRESS',
'EMPGRPSCHEDMM',
'EMPLOYMENTSTAT',
'GROUPSCHEDULE',
'HOLIDAY',
'JAIDS',
'LABORACCT',
'LABORACCTSET',
'LOGONPROFILE',
'ORGSET',
'OVERRIDETYPE',
'PAYCODE',
'PAYCODEDAP',
'PAYRULE',
'PAYRULEIDS',
'PERSON',
'PERSONEXPHRSMM',
'PERSONSTATUSMM',
'PHONENUMBER',
'POSTALADDRESS',
'PREFERENCEPROF',
'PRSNACCSASSIGN',
'PRSNLICTYPEMM',
'PUNCHEVENT',
'REPORTDAP',
'TERMINALRULE',
'TIMEENTRYTYPE',
'TIMESHEETITEM',
'TIMEZONE',
'TMSHTITEMTYPE',
'TOTALEVENTTS',
'USERACCOUNT',
'WAGEPROFILE',
'WDMDEVICEGROUP',
'WFCJOBORG',
'WORKERTYPE',
'WORKRULEDAP',
'WORKRULEIDS',
'WTKEMPLOYEE')
AND constraint_type='P'
order by table_name;

spool off
