SELECT AFTER.TIMESOURCE, AFTER.SECONDS-BEFORE.SECONDS ELAPSED_SECONDS 
FROM 
(
SELECT SID,EVENT TIMESOURCE,(TIME_WAITED/100) SECONDS 
FROM V$SESSION_EVENT 
WHERE SID=&&MONITORED_SID
UNION
SELECT SID,'CPU' TIMESOURCE,(VALUE/100) SECONDS 
FROM V$SESSTAT 
WHERE SID=&&MONITORED_SID
AND STATISTIC#=(SELECT STATISTIC# FROM V$STATNAME WHERE NAME='CPU used by this session')
UNION
SELECT SID,
'REALELAPSED' TIMESOURCE,
(SYSDATE-TO_DATE('01/01/1900','MM/DD/YYYY'))*24*60*60 SECONDS
FROM V$SESSION WHERE SID=&&MONITORED_SID
) AFTER,
BEFOREOTHERSESSION BEFORE
WHERE
BEFORE.SID=AFTER.SID AND
AFTER.TIMESOURCE=BEFORE.TIMESOURCE
ORDER BY ELAPSED_SECONDS DESC;

DROP TABLE BEFOREOTHERSESSION;

     
