UNDEFINE MONITORED_SID

DROP TABLE BEFOREOTHERSESSION;

CREATE TABLE BEFOREOTHERSESSION AS
SELECT s.SID,EVENT TIMESOURCE,(TIME_WAITED/100) SECONDS FROM V$SESSION_EVENT se,v$session s 
WHERE s.client_info like '%PSAPPSRV%' and
se.sid=s.sid;

INSERT INTO BEFOREOTHERSESSION SELECT s.SID,'CPU' TIMESOURCE,(VALUE/100) SECONDS 
FROM V$SESSTAT ss,v$session s
WHERE s.client_info like '%PSAPPSRV%' and
ss.sid=s.sid
AND STATISTIC#=(SELECT STATISTIC# FROM V$STATNAME WHERE NAME='CPU used by this session');

COMMIT;

INSERT INTO BEFOREOTHERSESSION
SELECT SID,
'REALELAPSED' TIMESOURCE,
(SYSDATE-TO_DATE('01/01/1900','MM/DD/YYYY'))*24*60*60 SECONDS
FROM V$SESSION 
WHERE client_info like '%PSAPPSRV%';

COMMIT;
