SELECT after.sid,AFTER.TIMESOURCE, AFTER.SECONDS-BEFORE.SECONDS ELAPSED_SECONDS 
FROM 
(
SELECT s.SID,EVENT TIMESOURCE,(TIME_WAITED/100) SECONDS 
FROM V$SESSION_EVENT se,v$session s  
WHERE s.USERNAME='TKCSOWNER' and
se.sid=s.sid
UNION
SELECT s.SID,'CPU' TIMESOURCE,(VALUE/100) SECONDS 
FROM V$SESSTAT ss,v$session s
WHERE s.USERNAME='TKCSOWNER' and
ss.sid=s.sid
AND STATISTIC#=(SELECT STATISTIC# FROM V$STATNAME WHERE NAME='CPU used by this session')
UNION
SELECT SID,
'REALELAPSED' TIMESOURCE,
(SYSDATE-TO_DATE('01/01/1900','MM/DD/YYYY'))*24*60*60 SECONDS
FROM V$SESSION WHERE USERNAME='TKCSOWNER'
) AFTER,
BEFOREOTHERSESSION BEFORE
WHERE
BEFORE.SID=AFTER.SID AND
AFTER.TIMESOURCE=BEFORE.TIMESOURCE
ORDER BY after.sid,ELAPSED_SECONDS DESC;

DROP TABLE BEFOREOTHERSESSION;

     
